const districtCoordinates = {
  "旺角": [22.3193, 114.1694],
  "旺角 / 佐敦": [22.312, 114.1707],
  "旺角 / 中環 / 灣仔 / 銅鑼灣": [22.29, 114.1715],
  "中環": [22.2819, 114.1586],
  "中環、銅鑼灣、尖沙咀、太古等": [22.289, 114.183],
  "灣仔": [22.2783, 114.1747],
  "銅鑼灣 / 尖沙咀": [22.2889, 114.179],
  "中環 / 金鐘": [22.2808, 114.162],
  "尖沙咀": [22.2976, 114.1722],
  "油麻地": [22.3133, 114.1709],
  "九龍城": [22.3282, 114.1887],
  "深水埗": [22.3305, 114.1622],
  "紅磡／黃埔": [22.3051, 114.1906],
  "太古": [22.2868, 114.2178],
  "尖沙咀／西九": [22.2991, 114.1596],
  "荔枝角": [22.3377, 114.148],
  "Sham Shui Po": [22.3305, 114.1622],
  "Hung Hom / Whampoa": [22.3051, 114.1906],
  "Taikoo": [22.2868, 114.2178],
  "Tsim Sha Tsui / West Kowloon": [22.2991, 114.1596],
  "Lai Chi Kok": [22.3377, 114.148],
  "Wan Chai": [22.2783, 114.1747],
  "Central": [22.2819, 114.1586],
  "Causeway Bay": [22.2802, 114.1843],
  "Tsim Sha Tsui": [22.2976, 114.1722],
  "Diamond Hill": [22.3402, 114.2017],
  "North Point": [22.2915, 114.2006],
  "Tin Hau": [22.2828, 114.1919],
  "Yau Ma Tei": [22.3133, 114.1709],
  "Tsuen Wan": [22.3717, 114.1131],
  "Kwai Chung": [22.3639, 114.1314],
  "Kwun Tong": [22.312, 114.226],
  "Wong Tai Sin": [22.3417, 114.1943],
  "Prince Edward": [22.3245, 114.1687],
  "Ma On Shan": [22.424, 114.231],
  "Mong Kok": [22.3193, 114.1694],
  "大埔": [22.4501, 114.1688],
  "沙田區": [22.3819, 114.1881],
  "Tai Po": [22.4501, 114.1688],
  "Sha Tin": [22.3819, 114.1881],
  "Tai Wai": [22.3727, 114.1786],
  "Fo Tan": [22.395, 114.198],
  "Jordan": [22.3043, 114.1716],
  "香港島／待核實分店": [22.282, 114.158],
  "待核實": [22.3027, 114.1772],
  "待核實分店": [22.3027, 114.1772],
};

function makeMenuItems(items) {
  return items.map((name) => ({ name, price: "", vegetarian: true }));
}

function makeRestaurant({
  name,
  district,
  category,
  cuisine,
  menuItems,
  sourceConfidence,
  sourceUrl,
  archiveName,
  brand,
  address,
  phone,
  hours,
  status,
  menuSource,
}) {
  const [lat, lng] = districtCoordinates[district] || districtCoordinates["待核實"];

  return {
    id: crypto.randomUUID(),
    name,
    archiveName: archiveName || name,
    brand: brand || name,
    category,
    cuisine,
    address: address || district,
    district,
    lat,
    lng,
    phone: phone || "",
    hours: hours || "",
    status: status || "",
    menuSource: menuSource || "",
    sourceConfidence,
    sourceUrl,
    notes: menuSource || `${cuisine}；${sourceConfidence}`,
    menuUpdatedAt: "2026-06-28",
    menuItems: makeMenuItems(menuItems),
  };
}

export const seedRestaurants = [
  makeRestaurant({
    name: "素年 YEARS 福華街",
    archiveName: "素年 YEARS 福華街",
    brand: "YEARS",
    district: "深水埗",
    address: "深水埗福華街191-199號 / 191-199 Fuk Wah Street",
    phone: "6338 3719",
    hours: "每日 12:00-22:00，last call 21:00",
    status: "Active / 高信心",
    category: "vegetarian",
    cuisine: "素食 / cafe",
    menuItems: ["weekday lunch menu", "weekday dinner menu", "weekend menu"],
    sourceConfidence: "Active / 高信心",
    sourceUrl: "",
    menuSource: "官方有 weekday lunch menu、weekday dinner & weekend menu 連結。",
  }),
  makeRestaurant({
    name: "素年 黃埔",
    archiveName: "素年 黃埔",
    brand: "Be with Years",
    district: "紅磡／黃埔",
    address: "紅磡黃埔天地百寶坊第3期地下G27號舖",
    phone: "9366 3261",
    hours: "日至四 11:30-21:30；五至六 11:30-22:00",
    status: "Active / 高信心",
    category: "vegetarian",
    cuisine: "素食 / cafe",
    menuItems: ["lunch menu", "dinner menu", "vegan pastry menu", "drinks / gelato menu"],
    sourceConfidence: "Active / 高信心",
    sourceUrl: "",
    menuSource: "官方有 lunch、dinner、vegan pastry、drinks / gelato menu；OpenRice 亦顯示同地址及電話。",
  }),
  makeRestaurant({
    name: "素年 太古",
    archiveName: "素年 太古",
    brand: "Here with Years",
    district: "太古",
    address: "太古城太裕路9號高安閣地下G517號舖",
    phone: "6601 9577",
    hours: "每日 11:30-21:30，last call 20:30",
    status: "Active / 高信心",
    category: "vegetarian",
    cuisine: "素食 / cafe",
    menuItems: ["weekday lunch menu", "weekend / after-3pm menu", "afternoon tea menu", "drink menu"],
    sourceConfidence: "Active / 高信心",
    sourceUrl: "",
    menuSource: "官方有 weekday lunch、weekend / after-3pm menu、afternoon tea、drink menu；OpenRice 亦確認地址、電話、營業時間。",
  }),
  makeRestaurant({
    name: "素年 西九文化區",
    archiveName: "素年 西九文化區",
    brand: "Play with Years",
    district: "尖沙咀／西九",
    address: "西九文化區藝術公園地下GF-05號舖",
    phone: "9390 5310",
    hours: "每日 08:00-21:00，last call 20:00",
    status: "Active / 高信心",
    category: "vegetarian",
    cuisine: "素食 / cafe",
    menuItems: ["breakfast menu", "main menu", "drink menu"],
    sourceConfidence: "Active / 高信心",
    sourceUrl: "",
    menuSource: "官方有 breakfast menu、main menu、drink menu。",
  }),
  makeRestaurant({
    name: "素年 荔枝角",
    archiveName: "素年 荔枝角",
    brand: "Bear by Years",
    district: "荔枝角",
    address: "荔枝角長裕街億京廣場二期地下2號舖",
    phone: "5336 4000",
    hours: "每日 08:00-22:00，last call 21:00",
    status: "Active / 高信心",
    category: "vegetarian",
    cuisine: "素食 / cafe",
    menuItems: ["breakfast menu", "lunch & dinner menu", "drink menu"],
    sourceConfidence: "Active / 高信心",
    sourceUrl: "",
    menuSource: "官方有 breakfast menu、lunch & dinner menu、drink menu。",
  }),
  makeRestaurant({
    name: "WANAKA by Years",
    archiveName: "WANAKA by Years Blue House Wan Chai",
    brand: "WANAKA by Years",
    district: "Wan Chai",
    address: "8 King Sing Street, Blue House, Wan Chai",
    status: "active",
    category: "vegetarian",
    cuisine: "Cafe / plant-based",
    menuItems: ["main menu", "drinks"],
    sourceConfidence: "A",
    sourceUrl: "https://www.yearshk.com/pages/menu",
    menuSource: "Official shops/menu page",
  }),
  makeRestaurant({
    name: "TREEHOUSE BaseHall Central",
    archiveName: "TREEHOUSE BaseHall Central",
    brand: "TREEHOUSE",
    district: "Central",
    address: "BaseHall, Shop 1, B1/F, Jardine House, 1 Connaught Place, Central",
    status: "active",
    category: "vegetarian",
    cuisine: "Plant-based fast casual",
    menuItems: ["sourdough flatbread wraps", "salad & grain bowls", "burgers", "falafel", "tempeh", "hummus"],
    sourceConfidence: "A",
    sourceUrl: "https://www.treehouse.eco/menu",
    menuSource: "Official menu + OpenRice address",
  }),
  makeRestaurant({
    name: "Woodlands Indian Vegetarian Restaurant TST",
    archiveName: "Woodlands Indian Vegetarian Restaurant Tsim Sha Tsui",
    brand: "Woodlands Indian Vegetarian Restaurant",
    district: "Tsim Sha Tsui",
    address: "UG16-17, Wing On Plaza, 62 Mody Road, TST East",
    status: "active",
    category: "vegetarian",
    cuisine: "Indian vegetarian",
    menuItems: ["South Indian thali", "North Indian thali", "dosa", "curries", "vegan menu"],
    sourceConfidence: "A",
    sourceUrl: "https://www.woodlandshk.com/tsim-sha-tsui/menu",
    menuSource: "Official menu + Foodpanda",
  }),
  makeRestaurant({
    name: "Woodlands Indian Vegetarian Restaurant Wan Chai",
    archiveName: "Woodlands Indian Vegetarian Restaurant Wan Chai",
    brand: "Woodlands Indian Vegetarian Restaurant",
    district: "Wan Chai",
    address: "1/F, Dannies House, 20 Luard Road, Wan Chai",
    status: "active",
    category: "vegetarian",
    cuisine: "Indian vegetarian",
    menuItems: ["paneer curries", "aloo mutter", "thali", "dosa"],
    sourceConfidence: "A",
    sourceUrl: "https://woodlandshk.com/",
    menuSource: "Official locations + Foodpanda",
  }),
  makeRestaurant({
    name: "Chi Lin Vegetarian / 龍門樓 志蓮素齋",
    archiveName: "Chi Lin Vegetarian / 龍門樓 志蓮素齋",
    brand: "Chi Lin Vegetarian",
    district: "Diamond Hill",
    address: "Long Men Lou, Nan Lian Garden, 60 Fung Tak Road, Diamond Hill",
    status: "active",
    category: "vegetarian",
    cuisine: "Cantonese vegetarian",
    menuItems: ["翡翠百福袋", "五福拼盤", "菠蘿咕嚕麥纖"],
    sourceConfidence: "A",
    sourceUrl: "https://www.openrice.com/zh/hongkong/r-%E9%BE%8D%E9%96%80%E6%A8%93-%E5%BF%97%E8%93%AE%E7%B4%A0%E9%BD%8B-%E9%91%BD%E7%9F%B3%E5%B1%B1-%E7%B2%B5%E8%8F%9C-%E5%BB%A3%E6%9D%B1-%E7%B4%A0%E9%A3%9F-r17526",
    menuSource: "OpenRice + booking page",
  }),
  makeRestaurant({
    name: "Gaia Veggie Shop 大自然素食 銅鑼灣",
    archiveName: "Gaia Veggie Shop 大自然素食 Causeway Bay",
    brand: "Gaia Veggie Shop 大自然素食",
    district: "Causeway Bay",
    address: "8/F, The Goldmark, 502 Hennessy Road, Causeway Bay",
    status: "active",
    category: "vegetarian",
    cuisine: "Hong Kong style vegetarian",
    menuItems: ["香芒吉列卷", "芋頭魚", "原盅黃耳素翅燉椰皇"],
    sourceConfidence: "A",
    sourceUrl: "https://www.openrice.com/zh/hongkong/r-%E5%A4%A7%E8%87%AA%E7%84%B6%E7%B4%A0%E9%A3%9F-%E9%8A%85%E9%91%BC%E7%81%A3-%E6%B8%AF%E5%BC%8F-%E7%B4%A0%E9%A3%9F-r22451",
    menuSource: "OpenRice + HappyCow",
  }),
  makeRestaurant({
    name: "Gaia Veggie Shop 大自然素食 尖沙咀",
    archiveName: "Gaia Veggie Shop 大自然素食 Tsim Sha Tsui",
    brand: "Gaia Veggie Shop 大自然素食",
    district: "Tsim Sha Tsui",
    address: "Shop 212, 2/F, Mira Place One, 132 Nathan Road, Tsim Sha Tsui",
    status: "active",
    category: "vegetarian",
    cuisine: "Hong Kong style vegetarian",
    menuItems: ["招牌雀巢三色骨", "法式牛油果焗多士"],
    sourceConfidence: "A",
    sourceUrl: "https://www.openrice.com/zh/hongkong/r-%E5%A4%A7%E8%87%AA%E7%84%B6%E7%B4%A0%E9%A3%9F-%E5%B0%96%E6%B2%99%E5%92%80-%E6%B8%AF%E5%BC%8F-%E7%B4%A0%E9%A3%9F-r38102",
    menuSource: "OpenRice",
  }),
  makeRestaurant({
    name: "Gaia Veggie Shop 大自然素食 太子",
    archiveName: "Gaia Veggie Shop 大自然素食 Prince Edward",
    brand: "Gaia Veggie Shop 大自然素食",
    district: "Prince Edward",
    address: "Shop 335, 3/F, Pioneer Centre, 750 Nathan Road, Prince Edward",
    status: "active",
    category: "vegetarian",
    cuisine: "Hong Kong style vegetarian",
    menuItems: ["芋頭魚", "燒汁雜菌焗牛仔肉", "原隻木瓜蟹籽沙律"],
    sourceConfidence: "A",
    sourceUrl: "https://www.openrice.com/zh/hongkong/r-%E5%A4%A7%E8%87%AA%E7%84%B6%E7%B4%A0%E9%A3%9F-%E5%A4%AA%E5%AD%90-%E6%B8%AF%E5%BC%8F-%E7%B4%A0%E9%A3%9F-r17714",
    menuSource: "OpenRice",
  }),
  makeRestaurant({
    name: "Pure Veggie House 心齋 Central",
    archiveName: "Pure Veggie House 心齋 Central / M88",
    brand: "Pure Veggie House 心齋",
    district: "Central",
    address: "6/F, M88, Wellington Place, 2-8 Wellington Street, Central",
    status: "active",
    category: "vegetarian",
    cuisine: "Cantonese vegetarian",
    menuItems: ["vegetarian Cantonese dishes", "hotpot noted in reviews"],
    sourceConfidence: "A",
    sourceUrl: "https://www.openrice.com/en/hongkong/r-pure-veggie-house-central-guangdong-meatless-menu-r636193",
    menuSource: "OpenRice says moved/new location",
  }),
  makeRestaurant({
    name: "Kung Tak Lam Shanghai Vegetarian 功德林上海素食",
    archiveName: "Kung Tak Lam Shanghai Vegetarian 功德林上海素食 Sugar+ Causeway Bay",
    brand: "Kung Tak Lam Shanghai Vegetarian 功德林上海素食",
    district: "Causeway Bay",
    address: "20/F, Sugar+, 25-31 Sugar Street, Causeway Bay",
    status: "active",
    category: "vegetarian",
    cuisine: "Shanghainese vegetarian",
    menuItems: ["皇菇黑松露炆黑豆腐", "梅菜扣素肉", "潮州素煎蠔餅"],
    sourceConfidence: "A",
    sourceUrl: "https://www.openrice.com/zh/hongkong/r-%E5%8A%9F%E5%BE%B7%E6%9E%97%E4%B8%8A%E6%B5%B7%E7%B4%A0%E9%A3%9F-%E9%8A%85%E9%91%BC-%E6%BB%AC%E8%8F%9C-%E4%B8%8A%E6%B5%B7-%E7%B4%A0%E9%A3%9F-r793570/menus",
    menuSource: "OpenRice active",
  }),
  makeRestaurant({
    name: "Green Veggie 天然齋",
    archiveName: "Green Veggie 天然齋 Wan Chai",
    brand: "Green Veggie 天然齋",
    district: "Wan Chai",
    address: "G/F, Block 11-12, David House, 254-272 Jaffe Road, Wan Chai",
    status: "active",
    category: "vegetarian",
    cuisine: "International / Chinese vegetarian",
    menuItems: ["招牌叉燒包", "姬松茸燉湯", "牛油果伴沙律"],
    sourceConfidence: "A",
    sourceUrl: "https://www.openrice.com/zh/hongkong/r-%E5%A4%A9%E7%84%B6%E9%BD%8B-%E7%81%A3%E4%BB%94-%E5%A4%9A%E5%9C%8B%E8%8F%9C-%E7%B4%A0%E9%A3%9F-r452555",
    menuSource: "OpenRice",
  }),
  makeRestaurant({
    name: "Tin Tin Vegetarian 天天素食",
    archiveName: "Tin Tin Vegetarian 天天素食 Tin Hau",
    brand: "Tin Tin Vegetarian 天天素食",
    district: "Tin Hau",
    address: "Shops G6-7, Apple Mall, 14 King's Road, Tin Hau",
    status: "active",
    category: "vegetarian",
    cuisine: "Cantonese vegetarian / takeaway",
    menuItems: ["savories", "mock meats", "sweet buns", "herbal drinks"],
    sourceConfidence: "A",
    sourceUrl: "https://www.openrice.com/zh/hongkong/r-%E5%A4%A9%E5%A4%A9%E7%B4%A0%E9%A3%9F-%E5%A4%A9%E5%90%8E-%E7%B2%B5%E8%8F%9C-%E5%BB%A3%E6%9D%B1-%E7%B4%A0%E9%A3%9F-r30333",
    menuSource: "OpenRice + HappyCow",
  }),
  makeRestaurant({
    name: "Everyday 每日",
    archiveName: "Everyday 每日 Tsim Sha Tsui",
    brand: "Everyday 每日",
    district: "Tsim Sha Tsui",
    address: "G/F, Shan Lam Court, 10-12 Hillwood Road, Tsim Sha Tsui",
    status: "active",
    category: "vegetarian",
    cuisine: "International vegetarian",
    menuItems: ["花生脆蘋果", "香蕉拔絲", "椒鹽豆腐", "素碗仔翅"],
    sourceConfidence: "A",
    sourceUrl: "https://www.openrice.com/zh/hongkong/r-%E6%AF%8F%E6%97%A5-%E5%B0%96%E6%B2%99%E5%92%80-%E5%A4%9A%E5%9C%8B%E8%8F%9C-%E7%B4%A0%E9%A3%9F-r584611",
    menuSource: "OpenRice",
  }),
  makeRestaurant({
    name: "Ying Vegetarian 瀛素食",
    archiveName: "Ying Vegetarian 瀛素食 Yau Ma Tei",
    brand: "Ying Vegetarian 瀛素食",
    district: "Yau Ma Tei",
    address: "G/F, Kam Lee Court, 61 Temple Street, Yau Ma Tei",
    status: "active",
    category: "vegetarian",
    cuisine: "Hong Kong style vegetarian",
    menuItems: ["軟殼蟹卷", "士多啤梨骨", "椒鹽淮山"],
    sourceConfidence: "A",
    sourceUrl: "https://www.openrice.com/zh/hongkong/r-%E7%80%9B%E7%B4%A0%E9%A3%9F-%E6%B2%B9%E9%BA%BB%E5%9C%B0-%E6%B8%AF%E5%BC%8F-%E7%B4%A0%E9%A3%9F-r55111",
    menuSource: "OpenRice",
  }),
  makeRestaurant({
    name: "Leisurely Veggie 雅悠蔬食",
    archiveName: "Leisurely Veggie 雅悠蔬食 Tsim Sha Tsui",
    brand: "Leisurely Veggie 雅悠蔬食",
    district: "Tsim Sha Tsui",
    address: "Shop B, 3/F, China Insurance Building, 48 Cameron Road, Tsim Sha Tsui",
    status: "active",
    category: "vegetarian",
    cuisine: "International vegetarian buffet",
    menuItems: ["香芒牛油果苜蓿芽手卷", "vegetarian buffet / fusion dishes"],
    sourceConfidence: "A",
    sourceUrl: "https://www.openrice.com/zh/hongkong/r-%E9%9B%85-%E6%82%A0%E8%94%AC%E9%A3%9F-%E5%B0%96%E6%B2%99%E5%92%80-%E5%A4%9A%E5%9C%8B%E8%8F%9C-%E7%B4%A0%E9%A3%9F-r513285",
    menuSource: "OpenRice + Weekend HK buffet article",
  }),
  makeRestaurant({
    name: "Treasure Vegetarian Restaurant 新聚寶素食",
    archiveName: "Treasure Vegetarian Restaurant 新聚寶素食 Sham Shui Po",
    brand: "Treasure Vegetarian Restaurant 新聚寶素食",
    district: "Sham Shui Po",
    address: "Shop 85, G/F, Man On Building, 79-85 Tai Po Road, Sham Shui Po",
    status: "active",
    category: "vegetarian",
    cuisine: "Cantonese vegetarian",
    menuItems: ["乾炒牛河"],
    sourceConfidence: "A",
    sourceUrl: "https://www.openrice.com/zh/hongkong/r-%E6%96%B0%E8%81%9A%E5%AF%B6%E7%B4%A0%E9%A3%9F-%E6%B7%B1%E6%B0%B4%E5%9F%97-%E7%B2%B5%E8%8F%9C-%E5%BB%A3%E6%9D%B1-%E7%B4%A0%E9%A3%9F-r145684",
    menuSource: "OpenRice",
  }),
  makeRestaurant({
    name: "So Yuet Hin 素悅軒",
    archiveName: "So Yuet Hin 素悅軒 Tsuen Wan",
    brand: "So Yuet Hin 素悅軒",
    district: "Tsuen Wan",
    address: "Shop 15, G/F, Hoi Ching House, 25 Chiu Wo Street, Tsuen Wan",
    status: "active",
    category: "vegetarian",
    cuisine: "Hong Kong style vegetarian / cart noodles",
    menuItems: ["vegetarian cart noodles", "pumpkin soup", "multiple toppings"],
    sourceConfidence: "A",
    sourceUrl: "https://www.openrice.com/zh/hongkong/r-%E7%B4%A0%E6%82%85%E8%BB%92-%E8%8D%83%E7%81%A3-%E6%B8%AF%E5%BC%8F-%E7%84%A1%E8%82%89%E9%A4%90%E5%96%AE-r173776",
    menuSource: "OpenRice + HappyCow NT favourites",
  }),
  makeRestaurant({
    name: "Amazing Kitchen 香積廚素食館",
    archiveName: "Amazing Kitchen 香積廚素食館 Mong Kok",
    brand: "Amazing Kitchen 香積廚素食館",
    district: "Mong Kok",
    address: "G/F, 110 Fa Yuen Street, Mong Kok",
    status: "active",
    category: "vegetarian",
    cuisine: "Cantonese / Hong Kong vegetarian",
    menuItems: ["tomato baked rice", "mixed stir-fried noodles/rice", "two-dish rice", "curry monkey head mushroom"],
    sourceConfidence: "A",
    sourceUrl: "https://www.openrice.com/zh/hongkong/r-%E9%A6%99%E7%A9%8D%E5%BB%9A%E7%B4%A0%E9%A3%9F%E9%A4%A8-%E6%97%BA%E8%A7%92-%E7%B2%B5%E8%8F%9C-%E5%BB%A3%E6%9D%B1-%E7%B4%A0%E9%A3%9F-r113720",
    menuSource: "OpenRice + official Wix menu",
  }),
  makeRestaurant({
    name: "The Alchemist Cafe 牧羊少年咖啡館",
    archiveName: "The Alchemist Cafe 牧羊少年咖啡館 Mong Kok / Grand Plaza",
    brand: "The Alchemist Cafe 牧羊少年咖啡館",
    district: "Mong Kok",
    address: "Grand Plaza, Mong Kok (exact shop to verify)",
    status: "active",
    category: "mixed",
    cuisine: "Western cafe",
    menuItems: ["Vegetarian Brunch", "vegan/vegetarian pasta options", "mushrooms", "eggplant", "avocado", "scrambled egg"],
    sourceConfidence: "A",
    sourceUrl: "https://www.foodpanda.hk/restaurant/kdpp/the-alchemist-cafe-mong-kok",
    menuSource: "Foodpanda dish-level menu",
  }),
  makeRestaurant({
    name: "Cafe Retour 意歐",
    archiveName: "Cafe Retour 意歐 Mong Kok",
    brand: "Cafe Retour 意歐",
    district: "Mong Kok",
    address: "G/F, 6 Tung Choi Street, Mong Kok",
    status: "active",
    category: "mixed",
    cuisine: "Western / baked potatoes",
    menuItems: ["Black truffle egg salad baked potato", "cheese spinach mushroom baked potato"],
    sourceConfidence: "B+",
    sourceUrl: "https://www.openrice.com/zh/hongkong/r-%E6%84%8F%E6%AD%90-%E6%97%BA%E8%A7%92-%E8%A5%BF%E5%BC%8F-%E7%84%A1%E8%82%89%E9%A4%90%E5%96%AE-r159169",
    menuSource: "OpenRice meatless-menu tag; verify current item list",
  }),
  makeRestaurant({
    name: "蓮花健康素食 Lotus Vegetarian Restaurant",
    archiveName: "蓮花健康素食 Lotus Vegetarian Restaurant Tai Po",
    brand: "蓮花健康素食",
    district: "大埔",
    address: "大埔廣福道80號德康樓地舖",
    status: "active",
    category: "vegetarian",
    cuisine: "粵菜 / 中式素食",
    menuItems: ["菠蘿咕嚕玉", "豆角肉崧煎蛋角", "乾燒伊麵"],
    sourceConfidence: "A",
    sourceUrl: "https://www.openrice.com/zh/hongkong/r-%E8%93%AE%E8%8A%B1%E5%81%A5%E5%BA%B7%E7%B4%A0%E9%A3%9F-%E5%A4%A7%E5%9F%94-%E7%B2%B5%E8%8F%9C-%E5%BB%A3%E6%9D%B1-%E7%B4%A0%E9%A3%9F-r647103",
    menuSource: "Tai Po pilot: OpenRice / HappyCow confirm address; menu items from OpenRice photos/reviews.",
  }),
  makeRestaurant({
    name: "慧食堂 Eat Well Canteen",
    archiveName: "慧食堂 Eat Well Canteen Old Tai Po Police Station",
    brand: "慧食堂 Eat Well Canteen",
    district: "大埔",
    address: "大埔運頭角里11號舊大埔警署",
    status: "active_verify_menu",
    category: "vegetarian",
    cuisine: "多國菜 / 素食 / 有機食品",
    menuItems: ["vegetarian organic canteen menu", "current menu to verify"],
    sourceConfidence: "B",
    sourceUrl: "https://www.openrice.com/zh/hongkong/r-%E6%85%A7%E9%A3%9F%E5%A0%82-%E5%A4%A7%E5%9F%94-%E5%A4%9A%E5%9C%8B%E8%8F%9C-%E6%9C%89%E6%A9%9F%E9%A3%9F%E5%93%81-r465007",
    menuSource: "Tai Po pilot: OpenRice confirms vegetarian/organic category and address; current menu extraction needed.",
  }),
  makeRestaurant({
    name: "V.W Vegan Cafe",
    archiveName: "V.W Vegan Cafe Tai Po",
    brand: "V.W Vegan Cafe",
    district: "大埔",
    address: "大埔寶湖道3號寶湖花園商場2樓227F-06號舖",
    status: "active_verify_status",
    category: "vegetarian",
    cuisine: "多國菜 / vegan cafe",
    menuItems: ["日式媽媽便當", "vegan chocolate coffee"],
    sourceConfidence: "B",
    sourceUrl: "https://www.openrice.com/en/hongkong/r-v-w-vegan-cafe-tai-po-international-vegetarian-r672530/reviews",
    menuSource: "Tai Po pilot: OpenRice confirms address; latest public snippet is 2024 so active status should be checked.",
  }),
  makeRestaurant({
    name: "Dough Bros Pizza & Doughnuts Tai Po",
    archiveName: "Dough Bros Pizza & Doughnuts Tai Po Mega Mall",
    brand: "Dough Bros Pizza & Doughnuts",
    district: "大埔",
    address: "大埔安邦路8-10號大埔超級城C區2樓587號舖",
    status: "active",
    category: "mixed",
    cuisine: "Pizza / doughnuts",
    menuItems: ["The Classic (V)", "The Veggie (V)", "The Truffle (V)"],
    sourceConfidence: "A",
    sourceUrl: "https://www.foodpanda.hk/restaurant/qnny/dough-bros-pizza-and-doughnuts-tai-po-mega-mall",
    menuSource: "Tai Po pilot: Foodpanda menu has explicit vegetarian pizza labels; exact shop number conflict noted.",
  }),
  makeRestaurant({
    name: "WM Cafe & Bar",
    archiveName: "WM Cafe & Bar Tai Po",
    brand: "WM Cafe & Bar",
    district: "大埔",
    address: "Tai Po address to verify",
    status: "active_verify_address",
    category: "mixed",
    cuisine: "西式 / pizza / pasta / risotto",
    menuItems: ["Portobello Mushroom and Mixed Mushroom Pizza", "Portobello Mushroom, Black Truffle and Mixed Mushroom Risotto"],
    sourceConfidence: "A",
    sourceUrl: "https://www.foodpanda.hk/restaurant/w0lm/wm-cafe-and-bar-tai-po",
    menuSource: "Tai Po pilot: Foodpanda marks vegetarian pizza and risotto; address still needs verification.",
  }),
  makeRestaurant({
    name: "Route 83 Tai Po",
    archiveName: "Route 83 Tai Po",
    brand: "Route 83",
    district: "大埔",
    address: "Tai Po address to verify",
    status: "active_verify_address",
    category: "mixed",
    cuisine: "西式 / handmade pizza",
    menuItems: ["Vegetarian Pizza"],
    sourceConfidence: "A",
    sourceUrl: "https://www.foodpanda.hk/restaurant/v3pf/route-83-tai-po",
    menuSource: "Tai Po pilot: Foodpanda has vegetarian pizza with cheddar, bell pepper, pineapple, mushroom and cherry tomato.",
  }),
  makeRestaurant({
    name: "三寶齋素食中心 Sam Bo Vegetarian Restaurant",
    archiveName: "三寶齋素食中心 Sam Bo Vegetarian Restaurant Sha Tin",
    brand: "三寶齋素食中心",
    district: "沙田區",
    address: "沙田沙田正街21-27號沙田廣場3樓商場33號舖",
    status: "active_verify_menu",
    category: "vegetarian",
    cuisine: "粵菜 / 港式素食",
    menuItems: ["粵式素食", "飯麵", "小炒"],
    sourceConfidence: "A",
    sourceUrl: "https://www.openrice.com/zh/hongkong/r-%E4%B8%89%E5%AF%B6%E9%BD%8B%E7%B4%A0%E9%A3%9F%E4%B8%AD%E5%BF%83-%E6%B2%99%E7%94%B0-%E7%B2%B5%E8%8F%9C-%E5%BB%A3%E6%9D%B1-%E7%B4%A0%E9%A3%9F-r5220",
    menuSource: "Sha Tin pilot: OpenRice has address and menu entry; menu photo extraction still needed.",
  }),
  makeRestaurant({
    name: "天天素食 Tin Tin Vegetarian Sha Tin",
    archiveName: "天天素食 Tin Tin Vegetarian Sha Tin Plaza",
    brand: "天天素食 Tin Tin Vegetarian",
    district: "沙田區",
    address: "沙田沙田正街21-27號沙田廣場3樓31A號舖",
    status: "active",
    category: "vegetarian",
    cuisine: "港式素食 / 外賣 / 點心",
    menuItems: ["素點心", "素叉燒包", "素燒賣", "春卷", "蘿蔔糕", "素菜煎包"],
    sourceConfidence: "A",
    sourceUrl: "https://www.happycow.net/",
    menuSource: "Sha Tin pilot: HappyCow and OpenRice confirm listing; takeaway vegetarian dim sum items.",
  }),
  makeRestaurant({
    name: "天賜素齋 Wo Che Estate Vegetarian Restaurant",
    archiveName: "天賜素齋 Wo Che Estate Vegetarian Restaurant",
    brand: "天賜素齋",
    district: "沙田區",
    address: "沙田德厚街3號禾輋廣場2樓220號舖",
    status: "active",
    category: "vegetarian",
    cuisine: "粵菜 / 港式素食",
    menuItems: ["齋鹵味", "乾炒牛河", "飯", "麵", "素肉", "蔬菜菜式"],
    sourceConfidence: "A",
    sourceUrl: "https://www.happycow.net/reviews/wo-che-estate-vegetarian-new-territories-206746",
    menuSource: "Sha Tin pilot: HappyCow + OpenRice; OpenRice main dishes include 齋鹵味 and 乾炒牛河.",
  }),
  makeRestaurant({
    name: "立成健康素食 Lap Shing Vegetarian",
    archiveName: "立成健康素食 Lap Shing Vegetarian Chun Shek",
    brand: "立成健康素食",
    district: "沙田區",
    address: "沙田盛田街1號秦石商場地下10B號舖",
    hours: "每日 10:00-19:00",
    status: "active",
    category: "vegetarian",
    cuisine: "港式素食 / 小食 / 外賣",
    menuItems: ["腐皮卷", "麵", "素吞拿飯團"],
    sourceConfidence: "A",
    sourceUrl: "https://www.happycow.net/reviews/lap-shing-vegetarian-new-territories-229833",
    menuSource: "Sha Tin pilot: HappyCow/OpenRice; HappyCow indicates daily 10:00-19:00.",
  }),
  makeRestaurant({
    name: "Dough Bros Pizza & Doughnuts Tai Wai",
    archiveName: "Dough Bros Pizza & Doughnuts Tai Wai",
    brand: "Dough Bros Pizza & Doughnuts",
    district: "沙田區",
    address: "大圍積德里15-19號隆亨樓地下A號舖",
    status: "active",
    category: "mixed",
    cuisine: "意大利菜 / Pizza / Fast food",
    menuItems: ["The Classic (V)", "The Veggie (V)", "The Truffle (V)"],
    sourceConfidence: "A",
    sourceUrl: "https://www.foodpanda.hk/restaurant/z4ou/dough-bros-pizza-and-doughnuts-tai-wai",
    menuSource: "Sha Tin pilot: Foodpanda has explicit vegetarian pizza labels.",
  }),
  makeRestaurant({
    name: "Beans The Greenhouse Sha Tin",
    archiveName: "Beans The Greenhouse Sha Tin",
    brand: "Beans The Greenhouse",
    district: "沙田區",
    address: "沙田沙田鄉事會路138號新城市中央廣場5樓503號舖",
    status: "active",
    category: "mixed",
    cuisine: "西式 / All-day breakfast / Cafe",
    menuItems: ["Pumpkin Risotto", "Black Truffle Mushroom Risotto", "Pistachio Pizza", "Margherita Pizza"],
    sourceConfidence: "A",
    sourceUrl: "https://www.foodpanda.hk/restaurant/bh3g/beans-the-greenhouse-sha-tin/reviews",
    menuSource: "Sha Tin pilot: Foodpanda/OpenRice show meatless risotto and pizza items.",
  }),
  makeRestaurant({
    name: "Din Tai Fung HK Sha Tin",
    archiveName: "Din Tai Fung HK New Town Plaza Sha Tin",
    brand: "Din Tai Fung HK",
    district: "沙田區",
    address: "沙田新城市廣場一期1樓166號舖",
    status: "active",
    category: "mixed",
    cuisine: "台灣菜 / 小籠包 / 麵食",
    menuItems: ["Double-Boiled Mixed Mushroom Soup", "Double-Boiled Mixed Mushroom Soup Served with Noodle"],
    sourceConfidence: "A",
    sourceUrl: "https://www.foodpanda.hk/restaurant/w0wb/din-tai-fung-hk-sha-tin",
    menuSource: "Sha Tin pilot: Foodpanda item-level vegetarian-friendly mushroom soup/noodle options.",
  }),
  makeRestaurant({
    name: "Sangeetha Vegetarian Restaurant",
    archiveName: "Sangeetha Vegetarian Restaurant Tsim Sha Tsui",
    brand: "Sangeetha Vegetarian Restaurant",
    district: "Tsim Sha Tsui",
    address: "Tsim Sha Tsui East address to verify",
    status: "active",
    category: "vegetarian",
    cuisine: "Indian / South Indian",
    menuItems: ["South Indian vegetarian breakfast", "thali", "snacks", "dinner"],
    sourceConfidence: "A",
    sourceUrl: "https://sangeetha.com.hk/",
    menuSource: "TST/Jordan pilot: Official/OpenRice/HappyCow sources show South Indian vegetarian menu.",
  }),
  makeRestaurant({
    name: "Light Vegetarian Restaurant",
    archiveName: "Light Vegetarian Restaurant Jordan",
    brand: "Light Vegetarian Restaurant",
    district: "Jordan",
    address: "Jordan address to verify",
    status: "active",
    category: "vegetarian",
    cuisine: "Cantonese / Chinese buffet & a la carte",
    menuItems: ["mostly vegan menu", "lunch buffet", "a la carte rice/noodles"],
    sourceConfidence: "A",
    sourceUrl: "https://www.openrice.com/en/hongkong/r-light-vegetarian-restaurant-jordan-guangdong-vegetarian-r1866",
    menuSource: "TST/Jordan pilot: OpenRice + HappyCow active listing.",
  }),
  makeRestaurant({
    name: "Three Virtues Vegetarian Restaurant Jordan",
    archiveName: "Three Virtues Vegetarian Restaurant JD Mall Jordan",
    brand: "Three Virtues Vegetarian Restaurant",
    district: "Jordan",
    address: "Jordan JD Mall address to verify",
    status: "active",
    category: "vegetarian",
    cuisine: "Cantonese / Chinese / dim sum",
    menuItems: ["Dim sum", "banquet dishes", "fried rice/noodles", "set menus"],
    sourceConfidence: "A",
    sourceUrl: "https://www.openrice.com/en/hongkong/r-three-virtues-vegetarian-restaurant-jordan-guangdong-vegetarian-r20523",
    menuSource: "TST/Jordan pilot: OpenRice + Foodpanda active listing.",
  }),
  makeRestaurant({
    name: "Lotus Vegetarian Restaurant Jordan",
    archiveName: "Lotus Vegetarian Restaurant Jordan",
    brand: "Lotus Vegetarian Restaurant",
    district: "Jordan",
    address: "Jordan address to verify",
    status: "active",
    category: "vegetarian",
    cuisine: "Cantonese / Chinese",
    menuItems: ["Cantonese vegetarian dishes", "set meals", "rice/noodle dishes"],
    sourceConfidence: "A",
    sourceUrl: "https://www.openrice.com/en/hongkong/r-lotus-vegetarian-restaurant-jordan-guangdong-vegetarian-r544535",
    menuSource: "TST/Jordan pilot: OpenRice + HappyCow active listing.",
  }),
  makeRestaurant({
    name: "Via Vegetarian Restaurant",
    archiveName: "Via Vegetarian Restaurant Jordan",
    brand: "Via Vegetarian Restaurant",
    district: "Jordan",
    address: "Jordan address to verify",
    status: "active",
    category: "vegetarian",
    cuisine: "Hong Kong style vegetarian",
    menuItems: ["Hong Kong style vegetarian dishes"],
    sourceConfidence: "A",
    sourceUrl: "https://www.openrice.com/en/hongkong/r-via-vegetarian-restaurant-jordan-hong-kong-style-vegetarian-r747297",
    menuSource: "TST/Jordan pilot: OpenRice active listing.",
  }),
  makeRestaurant({
    name: "Sino Vegetarian Restaurant",
    archiveName: "Sino Vegetarian Restaurant Jordan",
    brand: "Sino Vegetarian Restaurant",
    district: "Jordan",
    address: "Jordan address to verify",
    status: "active",
    category: "vegetarian",
    cuisine: "Hong Kong style vegetarian",
    menuItems: ["Hong Kong style vegetarian dishes"],
    sourceConfidence: "A",
    sourceUrl: "https://www.openrice.com/en/hongkong/r-sino-vegetarian-restaurant-jordan-hong-kong-style-vegetarian-r25363",
    menuSource: "TST/Jordan pilot: OpenRice active listing.",
  }),
  makeRestaurant({
    name: "Gaylord Indian Restaurant",
    archiveName: "Gaylord Indian Restaurant Tsim Sha Tsui",
    brand: "Gaylord Indian Restaurant",
    district: "Tsim Sha Tsui",
    address: "Tsim Sha Tsui address to verify",
    status: "active",
    category: "mixed",
    cuisine: "Indian",
    menuItems: ["Paneer Makhani", "Malai Kofta", "Saag Paneer", "Aloo Gobi", "Kadai Vegetables", "Chole"],
    sourceConfidence: "A",
    sourceUrl: "https://www.foodpanda.hk/restaurant/s2on/gaylord-indian-restaurant",
    menuSource: "TST/Jordan pilot: Foodpanda and official menu show vegetarian delights.",
  }),
  makeRestaurant({
    name: "Pici Tsim Sha Tsui",
    archiveName: "Pici Tsim Sha Tsui",
    brand: "Pici",
    district: "Tsim Sha Tsui",
    address: "Tsim Sha Tsui address to verify",
    status: "active",
    category: "mixed",
    cuisine: "Italian / pasta",
    menuItems: ["Tagliolini Truffle (V)", "Tagliolini Arrabbiata (V)"],
    sourceConfidence: "A",
    sourceUrl: "https://www.foodpanda.hk/restaurant/uutd/pici-tsim-sha-tsui",
    menuSource: "TST/Jordan pilot: Foodpanda marks vegetarian pasta items.",
  }),
  makeRestaurant({
    name: "King Lam Chinese Noodles Restaurant Jordan",
    archiveName: "King Lam Chinese Noodles Restaurant Jordan",
    brand: "King Lam Chinese Noodles Restaurant",
    district: "Jordan",
    address: "Jordan address to verify",
    status: "active",
    category: "mixed",
    cuisine: "Chinese noodles",
    menuItems: ["Healthy Vegetarian Set A", "Healthy Vegetarian Set B", "Healthy Vegetarian Set C", "Healthy Vegetarian Set D"],
    sourceConfidence: "A",
    sourceUrl: "https://www.foodpanda.hk/restaurant/v0ok/king-lam-chinese-noodles-restaurant-jordan",
    menuSource: "TST/Jordan pilot: Foodpanda shows natural vegetarian soup base sets.",
  }),
  makeRestaurant({
    name: "Lady 13 Kitchen",
    district: "旺角 / 佐敦",
    category: "mixed",
    cuisine: "港式飯麵",
    menuItems: [
      "麻辣素手撕雞飯",
      "Seared Soya Chicken Rice Bowl",
      "Seared Soya Chicken Noodle Soup",
      "Mala Soya Chicken Noodle Soup",
    ],
    sourceConfidence: "Foodpanda 有獨立 Vegetarian Menu；A 級",
    sourceUrl: "https://www.foodpanda.hk/restaurant/v9au/lady-13-kitchen-mong-kok",
  }),
  makeRestaurant({
    name: "Alice Pizza",
    district: "旺角 / 中環 / 灣仔 / 銅鑼灣",
    category: "mixed",
    cuisine: "意式薄餅",
    menuItems: ["4 Formaggi Pizza", "Primavera Pizza", "Spicy Potatoes Pizza"],
    sourceConfidence: "Foodpanda 有 Vegetarian Pizza section；A 級",
    sourceUrl: "https://www.foodpanda.hk/restaurant/jg2x/alice-pizza-mong-kok",
  }),
  makeRestaurant({
    name: "13 Mui Fusion Cafe",
    district: "旺角",
    category: "mixed",
    cuisine: "Cafe / 西式",
    menuItems: ["Earth Energy Bowl", "Future All Day Breakfast"],
    sourceConfidence: "Foodpanda 顯示 vegetarian chicken leg、avocado、beans、scrambled eggs 等主食配搭；A 級",
    sourceUrl: "https://www.foodpanda.hk/restaurant/d2qj/13-mui-fusion-cafe-mong-kok-d2qj",
  }),
  makeRestaurant({
    name: "Spice of India",
    district: "旺角",
    category: "mixed",
    cuisine: "印度菜",
    menuItems: ["Aloo Gobi", "Palak Paneer", "Channa Masala", "Dal", "Vegetable Biryani 類"],
    sourceConfidence: "Foodpanda / OpenRice 可見 vegetarian 印度選項；A 級",
    sourceUrl: "https://www.foodpanda.hk/",
  }),
  makeRestaurant({
    name: "Miss India 旺角咖喱屋",
    district: "旺角",
    category: "mixed",
    cuisine: "印度菜",
    menuItems: ["Veg Samosa", "Vegetable Curry", "Vegetable Biryani", "naan / roti 類"],
    sourceConfidence: "HappyCow 類平台及外賣餐牌可作交叉確認；A-/B+",
    sourceUrl: "",
  }),
  makeRestaurant({
    name: "The Curry Factory",
    district: "香港島／待核實分店",
    category: "mixed",
    cuisine: "印度菜",
    menuItems: ["Yellow Dal Tadka", "Palak Paneer", "Mix Vegetables"],
    sourceConfidence: "Foodpanda 顯示 Vegetarian Curry section；A 級",
    sourceUrl: "https://www.foodpanda.hk/restaurant/cb92/the-curry-factory/reviews",
  }),
  makeRestaurant({
    name: "Tikka Taco Panda",
    district: "油麻地",
    category: "mixed",
    cuisine: "Indian fusion",
    menuItems: ["Aloo Gobhi 等 vegetarian curry"],
    sourceConfidence: "Foodpanda 顯示 vegetarian curry item；B+",
    sourceUrl: "https://www.foodpanda.hk/restaurant/uies/tikka-taco-panda-yau-ma-tei",
  }),
  makeRestaurant({
    name: "PaPa Gomes",
    district: "待核實",
    category: "mixed",
    cuisine: "印度 / Goan",
    menuItems: ["Vegetarian curry 類"],
    sourceConfidence: "Foodpanda 有 vegetarian curry 描述；B",
    sourceUrl: "https://www.foodpanda.hk/restaurant/w5mv/papa-gomes",
  }),
  makeRestaurant({
    name: "Paisano's",
    district: "尖沙咀",
    category: "mixed",
    cuisine: "Pizza",
    menuItems: ["Vegetarian Pizza slice"],
    sourceConfidence: "Foodpanda 顯示 Vegetarian Pizza；B+",
    sourceUrl: "https://www.foodpanda.hk/restaurant/s5hs/paisanos-tst",
  }),
  makeRestaurant({
    name: "Dim Dim Sum",
    district: "旺角",
    category: "mixed",
    cuisine: "點心",
    menuItems: ["Taro and Vegetarian Filling Spring Roll"],
    sourceConfidence: "Foodpanda 顯示 vegetarian filling spring roll；C，因為較似小食，未必足夠作主食",
    sourceUrl: "https://www.foodpanda.hk/restaurant/ytnr/dim-dim-sum-mong-kok",
  }),
  makeRestaurant({
    name: "PizzaExpress",
    district: "旺角 / 中環 / 灣仔 / 銅鑼灣",
    category: "mixed",
    cuisine: "意大利菜",
    menuItems: ["Margherita", "Giardiniera", "Trifolata", "Penne ai Funghi", "Zucchini Lasagna"],
    sourceConfidence: "官方 vegetarian menu / OpenRice；A 級",
    sourceUrl: "https://www.pizzaexpress.hk/",
  }),
  makeRestaurant({
    name: "Kedai Kopi Semua Semua",
    district: "旺角",
    category: "mixed",
    cuisine: "馬來西亞菜",
    menuItems: ["Roti Canai with Curry", "Rojak Tauhu Goreng", "Kaya Toast"],
    sourceConfidence: "Foodpanda 有 vegetarian 標示；B+",
    sourceUrl: "",
  }),
  makeRestaurant({
    name: "TREEHOUSE",
    district: "中環、銅鑼灣、尖沙咀、太古等",
    category: "vegetarian",
    cuisine: "Plant-based / vegetarian",
    menuItems: [
      "flatbread wraps",
      "salad & grain bowls",
      "plant-based burgers",
      "falafel",
      "tempeh",
      "hummus",
    ],
    sourceConfidence: "官方網站列出多間分店；HappyCow 描述 menu 有 wraps、grain bowls、burgers 等；A 級",
    sourceUrl: "https://www.treehouse.eco/",
  }),
  makeRestaurant({
    name: "Veggie Kingdom 緻素坊",
    district: "銅鑼灣 / 尖沙咀",
    category: "vegetarian",
    cuisine: "中式素食 / 點心",
    menuItems: ["素北京鴨", "素蝦餃", "素燒賣", "腸粉等"],
    sourceConfidence: "SassyHK 2025 推介提到中式素食及點心；A-/B+",
    sourceUrl: "https://www.sassyhongkong.com/eat-drink-vegan-restaurants-veggie-friendly-health/",
  }),
  makeRestaurant({
    name: "LockCha 樂茶軒",
    district: "中環 / 金鐘",
    category: "vegetarian",
    cuisine: "素食茶館 / 點心",
    menuItems: ["Bean curd rolls", "siu mai", "pan-fried rice roll with XO sauce 等"],
    sourceConfidence: "Green Queen 2025 推介；B+",
    sourceUrl: "https://www.greenqueen.com.hk/best-vegan-vegetarian-restaurants-hong-kong-2025/",
  }),
  makeRestaurant({
    name: "Isoya Japanese Vegetarian",
    district: "灣仔",
    category: "vegetarian",
    cuisine: "日式素食",
    menuItems: ["tofu tasting plate", "veggie sushi", "tomato sashimi", "tasting menu 可 vegan upon request"],
    sourceConfidence: "Green Queen 2025 推介；B+",
    sourceUrl: "https://www.greenqueen.com.hk/best-vegan-vegetarian-restaurants-hong-kong-2025/",
  }),
  makeRestaurant({
    name: "Root Vegan",
    district: "中環",
    category: "vegetarian",
    cuisine: "Vegan / Pan-Asian",
    menuItems: ["khao soi with soy drumsticks", "seasonal pan-Asian dishes", "vegan cakes"],
    sourceConfidence: "Green Queen 2025 推介；B+",
    sourceUrl: "https://www.greenqueen.com.hk/best-vegan-vegetarian-restaurants-hong-kong-2025/",
  }),
  makeRestaurant({
    name: "LN Fortunate Coffee",
    district: "待核實分店",
    category: "vegetarian",
    cuisine: "100% plant-based cafe",
    menuItems: ["vegan Hong Kong French toast", "bubble waffles", "hot dogs with tofu sausage"],
    sourceConfidence: "Green Queen 2025 推介；B+",
    sourceUrl: "https://www.greenqueen.com.hk/best-vegan-vegetarian-restaurants-hong-kong-2025/",
  }),
  makeRestaurant({
    name: "Kailash Parbat",
    district: "尖沙咀",
    category: "vegetarian",
    cuisine: "印度素食",
    menuItems: ["paneer lababdaar", "dal makhani", "chaats", "tikkas", "kulfi"],
    sourceConfidence: "SassyHK 2025 推介；A-/B+",
    sourceUrl: "https://www.sassyhongkong.com/eat-drink-vegan-restaurants-veggie-friendly-health/",
  }),
  makeRestaurant({
    name: "OVO Cafe",
    district: "灣仔",
    category: "vegetarian",
    cuisine: "Vegetarian cafe",
    menuItems: ["vegetarian dishes", "soup of the day", "faux-meat dishes"],
    sourceConfidence: "SassyHK 2025 推介；B",
    sourceUrl: "https://www.sassyhongkong.com/eat-drink-vegan-restaurants-veggie-friendly-health/",
  }),
  makeRestaurant({
    name: "Veggie4Love",
    district: "中環",
    category: "vegetarian",
    cuisine: "素食 / fusion",
    menuItems: ["中西 fusion 素食主菜"],
    sourceConfidence: "SassyHK 2025 推介；B",
    sourceUrl: "https://www.sassyhongkong.com/eat-drink-vegan-restaurants-veggie-friendly-health/",
  }),
  makeRestaurant({
    name: "Thai Vegetarian Food",
    district: "九龍城",
    category: "vegetarian",
    cuisine: "泰式素食",
    menuItems: ["Thai vegetarian dishes", "set lunch"],
    sourceConfidence: "SassyHK 2025 推介；B",
    sourceUrl: "https://www.sassyhongkong.com/eat-drink-vegan-restaurants-veggie-friendly-health/",
  }),
  makeRestaurant({
    name: "無肉食 Ahimsa Buffet",
    district: "旺角",
    category: "vegetarian",
    cuisine: "素食 buffet",
    menuItems: ["Healthy Vegetarian Box A", "Healthy Vegetarian Box B", "Healthy Vegetarian Box C", "Healthy Vegetarian Box D", "素食 buffet / 飯盒"],
    sourceConfidence: "Foodpanda 顯示 vegetarian box；OpenRice 顯示旺角洗衣街分店為素食 / 無肉餐單；A 級",
    sourceUrl: "https://www.foodpanda.hk/restaurant/w6pk/ahimsa-buffet-mong-kok",
  }),
  makeRestaurant({
    name: "十三妹 Veggie Cafe",
    district: "旺角",
    category: "vegetarian",
    cuisine: "素食 cafe",
    menuItems: ["Earth Energy Bowl", "Future All Day Breakfast 等"],
    sourceConfidence: "Foodpanda / OpenRice 皆有資料；A-/B+",
    sourceUrl: "https://www.foodpanda.hk/restaurant/d2qj/13-mui-fusion-cafe-mong-kok-d2qj",
  }),
];
