const districtCoordinates = {
  "旺角": [22.3193, 114.1694],
  "旺角 / 佐敦": [22.312, 114.1707],
  "旺角 / 中環 / 灣仔 / 銅鑼灣": [22.29, 114.1715],
  "中環": [22.2819, 114.1586],
  "中環、銅鑼灣、尖沙咀、太古等": [22.289, 114.183],
  "灣仔": [22.2783, 114.1747],
  "銅鑼灣 / 尖沙咀": [22.2889, 114.179],
  "中環 / 金鐘": [22.2808, 114.162],
  "尖沙咀": [22.2976, 114.1722],
  "油麻地": [22.3133, 114.1709],
  "九龍城": [22.3282, 114.1887],
  "深水埗": [22.3305, 114.1622],
  "紅磡／黃埔": [22.3051, 114.1906],
  "太古": [22.2868, 114.2178],
  "尖沙咀／西九": [22.2991, 114.1596],
  "荔枝角": [22.3377, 114.148],
  "香港島／待核實分店": [22.282, 114.158],
  "待核實": [22.3027, 114.1772],
  "待核實分店": [22.3027, 114.1772],
};

function makeMenuItems(items) {
  return items.map((name) => ({ name, price: "", vegetarian: true }));
}

function makeRestaurant({
  name,
  district,
  category,
  cuisine,
  menuItems,
  sourceConfidence,
  sourceUrl,
  archiveName,
  brand,
  address,
  phone,
  hours,
  status,
  menuSource,
}) {
  const [lat, lng] = districtCoordinates[district] || districtCoordinates["待核實"];

  return {
    id: crypto.randomUUID(),
    name,
    archiveName: archiveName || name,
    brand: brand || name,
    category,
    cuisine,
    address: address || district,
    district,
    lat,
    lng,
    phone: phone || "",
    hours: hours || "",
    status: status || "",
    menuSource: menuSource || "",
    sourceConfidence,
    sourceUrl,
    notes: menuSource || `${cuisine}；${sourceConfidence}`,
    menuUpdatedAt: "2026-06-28",
    menuItems: makeMenuItems(menuItems),
  };
}

export const seedRestaurants = [
  makeRestaurant({
    name: "素年 YEARS 福華街",
    archiveName: "素年 YEARS 福華街",
    brand: "YEARS",
    district: "深水埗",
    address: "深水埗福華街191-199號 / 191-199 Fuk Wah Street",
    phone: "6338 3719",
    hours: "每日 12:00-22:00，last call 21:00",
    status: "Active / 高信心",
    category: "vegetarian",
    cuisine: "素食 / cafe",
    menuItems: ["weekday lunch menu", "weekday dinner menu", "weekend menu"],
    sourceConfidence: "Active / 高信心",
    sourceUrl: "",
    menuSource: "官方有 weekday lunch menu、weekday dinner & weekend menu 連結。",
  }),
  makeRestaurant({
    name: "素年 黃埔",
    archiveName: "素年 黃埔",
    brand: "Be with Years",
    district: "紅磡／黃埔",
    address: "紅磡黃埔天地百寶坊第3期地下G27號舖",
    phone: "9366 3261",
    hours: "日至四 11:30-21:30；五至六 11:30-22:00",
    status: "Active / 高信心",
    category: "vegetarian",
    cuisine: "素食 / cafe",
    menuItems: ["lunch menu", "dinner menu", "vegan pastry menu", "drinks / gelato menu"],
    sourceConfidence: "Active / 高信心",
    sourceUrl: "",
    menuSource: "官方有 lunch、dinner、vegan pastry、drinks / gelato menu；OpenRice 亦顯示同地址及電話。",
  }),
  makeRestaurant({
    name: "素年 太古",
    archiveName: "素年 太古",
    brand: "Here with Years",
    district: "太古",
    address: "太古城太裕路9號高安閣地下G517號舖",
    phone: "6601 9577",
    hours: "每日 11:30-21:30，last call 20:30",
    status: "Active / 高信心",
    category: "vegetarian",
    cuisine: "素食 / cafe",
    menuItems: ["weekday lunch menu", "weekend / after-3pm menu", "afternoon tea menu", "drink menu"],
    sourceConfidence: "Active / 高信心",
    sourceUrl: "",
    menuSource: "官方有 weekday lunch、weekend / after-3pm menu、afternoon tea、drink menu；OpenRice 亦確認地址、電話、營業時間。",
  }),
  makeRestaurant({
    name: "素年 西九文化區",
    archiveName: "素年 西九文化區",
    brand: "Play with Years",
    district: "尖沙咀／西九",
    address: "西九文化區藝術公園地下GF-05號舖",
    phone: "9390 5310",
    hours: "每日 08:00-21:00，last call 20:00",
    status: "Active / 高信心",
    category: "vegetarian",
    cuisine: "素食 / cafe",
    menuItems: ["breakfast menu", "main menu", "drink menu"],
    sourceConfidence: "Active / 高信心",
    sourceUrl: "",
    menuSource: "官方有 breakfast menu、main menu、drink menu。",
  }),
  makeRestaurant({
    name: "素年 荔枝角",
    archiveName: "素年 荔枝角",
    brand: "Bear by Years",
    district: "荔枝角",
    address: "荔枝角長裕街億京廣場二期地下2號舖",
    phone: "5336 4000",
    hours: "每日 08:00-22:00，last call 21:00",
    status: "Active / 高信心",
    category: "vegetarian",
    cuisine: "素食 / cafe",
    menuItems: ["breakfast menu", "lunch & dinner menu", "drink menu"],
    sourceConfidence: "Active / 高信心",
    sourceUrl: "",
    menuSource: "官方有 breakfast menu、lunch & dinner menu、drink menu。",
  }),
  makeRestaurant({
    name: "Lady 13 Kitchen",
    district: "旺角 / 佐敦",
    category: "mixed",
    cuisine: "港式飯麵",
    menuItems: [
      "麻辣素手撕雞飯",
      "Seared Soya Chicken Rice Bowl",
      "Seared Soya Chicken Noodle Soup",
      "Mala Soya Chicken Noodle Soup",
    ],
    sourceConfidence: "Foodpanda 有獨立 Vegetarian Menu；A 級",
    sourceUrl: "https://www.foodpanda.hk/restaurant/v9au/lady-13-kitchen-mong-kok",
  }),
  makeRestaurant({
    name: "Alice Pizza",
    district: "旺角 / 中環 / 灣仔 / 銅鑼灣",
    category: "mixed",
    cuisine: "意式薄餅",
    menuItems: ["4 Formaggi Pizza", "Primavera Pizza", "Spicy Potatoes Pizza"],
    sourceConfidence: "Foodpanda 有 Vegetarian Pizza section；A 級",
    sourceUrl: "https://www.foodpanda.hk/restaurant/jg2x/alice-pizza-mong-kok",
  }),
  makeRestaurant({
    name: "13 Mui Fusion Cafe",
    district: "旺角",
    category: "mixed",
    cuisine: "Cafe / 西式",
    menuItems: ["Earth Energy Bowl", "Future All Day Breakfast"],
    sourceConfidence: "Foodpanda 顯示 vegetarian chicken leg、avocado、beans、scrambled eggs 等主食配搭；A 級",
    sourceUrl: "https://www.foodpanda.hk/restaurant/d2qj/13-mui-fusion-cafe-mong-kok-d2qj",
  }),
  makeRestaurant({
    name: "Spice of India",
    district: "旺角",
    category: "mixed",
    cuisine: "印度菜",
    menuItems: ["Aloo Gobi", "Palak Paneer", "Channa Masala", "Dal", "Vegetable Biryani 類"],
    sourceConfidence: "Foodpanda / OpenRice 可見 vegetarian 印度選項；A 級",
    sourceUrl: "https://www.foodpanda.hk/",
  }),
  makeRestaurant({
    name: "Miss India 旺角咖喱屋",
    district: "旺角",
    category: "mixed",
    cuisine: "印度菜",
    menuItems: ["Veg Samosa", "Vegetable Curry", "Vegetable Biryani", "naan / roti 類"],
    sourceConfidence: "HappyCow 類平台及外賣餐牌可作交叉確認；A-/B+",
    sourceUrl: "",
  }),
  makeRestaurant({
    name: "The Curry Factory",
    district: "香港島／待核實分店",
    category: "mixed",
    cuisine: "印度菜",
    menuItems: ["Yellow Dal Tadka", "Palak Paneer", "Mix Vegetables"],
    sourceConfidence: "Foodpanda 顯示 Vegetarian Curry section；A 級",
    sourceUrl: "https://www.foodpanda.hk/restaurant/cb92/the-curry-factory/reviews",
  }),
  makeRestaurant({
    name: "Tikka Taco Panda",
    district: "油麻地",
    category: "mixed",
    cuisine: "Indian fusion",
    menuItems: ["Aloo Gobhi 等 vegetarian curry"],
    sourceConfidence: "Foodpanda 顯示 vegetarian curry item；B+",
    sourceUrl: "https://www.foodpanda.hk/restaurant/uies/tikka-taco-panda-yau-ma-tei",
  }),
  makeRestaurant({
    name: "PaPa Gomes",
    district: "待核實",
    category: "mixed",
    cuisine: "印度 / Goan",
    menuItems: ["Vegetarian curry 類"],
    sourceConfidence: "Foodpanda 有 vegetarian curry 描述；B",
    sourceUrl: "https://www.foodpanda.hk/restaurant/w5mv/papa-gomes",
  }),
  makeRestaurant({
    name: "Paisano's",
    district: "尖沙咀",
    category: "mixed",
    cuisine: "Pizza",
    menuItems: ["Vegetarian Pizza slice"],
    sourceConfidence: "Foodpanda 顯示 Vegetarian Pizza；B+",
    sourceUrl: "https://www.foodpanda.hk/restaurant/s5hs/paisanos-tst",
  }),
  makeRestaurant({
    name: "Dim Dim Sum",
    district: "旺角",
    category: "mixed",
    cuisine: "點心",
    menuItems: ["Taro and Vegetarian Filling Spring Roll"],
    sourceConfidence: "Foodpanda 顯示 vegetarian filling spring roll；C，因為較似小食，未必足夠作主食",
    sourceUrl: "https://www.foodpanda.hk/restaurant/ytnr/dim-dim-sum-mong-kok",
  }),
  makeRestaurant({
    name: "PizzaExpress",
    district: "旺角 / 中環 / 灣仔 / 銅鑼灣",
    category: "mixed",
    cuisine: "意大利菜",
    menuItems: ["Margherita", "Giardiniera", "Trifolata", "Penne ai Funghi", "Zucchini Lasagna"],
    sourceConfidence: "官方 vegetarian menu / OpenRice；A 級",
    sourceUrl: "https://www.pizzaexpress.hk/",
  }),
  makeRestaurant({
    name: "Kedai Kopi Semua Semua",
    district: "旺角",
    category: "mixed",
    cuisine: "馬來西亞菜",
    menuItems: ["Roti Canai with Curry", "Rojak Tauhu Goreng", "Kaya Toast"],
    sourceConfidence: "Foodpanda 有 vegetarian 標示；B+",
    sourceUrl: "",
  }),
  makeRestaurant({
    name: "TREEHOUSE",
    district: "中環、銅鑼灣、尖沙咀、太古等",
    category: "vegetarian",
    cuisine: "Plant-based / vegetarian",
    menuItems: [
      "flatbread wraps",
      "salad & grain bowls",
      "plant-based burgers",
      "falafel",
      "tempeh",
      "hummus",
    ],
    sourceConfidence: "官方網站列出多間分店；HappyCow 描述 menu 有 wraps、grain bowls、burgers 等；A 級",
    sourceUrl: "https://www.treehouse.eco/",
  }),
  makeRestaurant({
    name: "Veggie Kingdom 緻素坊",
    district: "銅鑼灣 / 尖沙咀",
    category: "vegetarian",
    cuisine: "中式素食 / 點心",
    menuItems: ["素北京鴨", "素蝦餃", "素燒賣", "腸粉等"],
    sourceConfidence: "SassyHK 2025 推介提到中式素食及點心；A-/B+",
    sourceUrl: "https://www.sassyhongkong.com/eat-drink-vegan-restaurants-veggie-friendly-health/",
  }),
  makeRestaurant({
    name: "LockCha 樂茶軒",
    district: "中環 / 金鐘",
    category: "vegetarian",
    cuisine: "素食茶館 / 點心",
    menuItems: ["Bean curd rolls", "siu mai", "pan-fried rice roll with XO sauce 等"],
    sourceConfidence: "Green Queen 2025 推介；B+",
    sourceUrl: "https://www.greenqueen.com.hk/best-vegan-vegetarian-restaurants-hong-kong-2025/",
  }),
  makeRestaurant({
    name: "Isoya Japanese Vegetarian",
    district: "灣仔",
    category: "vegetarian",
    cuisine: "日式素食",
    menuItems: ["tofu tasting plate", "veggie sushi", "tomato sashimi", "tasting menu 可 vegan upon request"],
    sourceConfidence: "Green Queen 2025 推介；B+",
    sourceUrl: "https://www.greenqueen.com.hk/best-vegan-vegetarian-restaurants-hong-kong-2025/",
  }),
  makeRestaurant({
    name: "Root Vegan",
    district: "中環",
    category: "vegetarian",
    cuisine: "Vegan / Pan-Asian",
    menuItems: ["khao soi with soy drumsticks", "seasonal pan-Asian dishes", "vegan cakes"],
    sourceConfidence: "Green Queen 2025 推介；B+",
    sourceUrl: "https://www.greenqueen.com.hk/best-vegan-vegetarian-restaurants-hong-kong-2025/",
  }),
  makeRestaurant({
    name: "LN Fortunate Coffee",
    district: "待核實分店",
    category: "vegetarian",
    cuisine: "100% plant-based cafe",
    menuItems: ["vegan Hong Kong French toast", "bubble waffles", "hot dogs with tofu sausage"],
    sourceConfidence: "Green Queen 2025 推介；B+",
    sourceUrl: "https://www.greenqueen.com.hk/best-vegan-vegetarian-restaurants-hong-kong-2025/",
  }),
  makeRestaurant({
    name: "Kailash Parbat",
    district: "尖沙咀",
    category: "vegetarian",
    cuisine: "印度素食",
    menuItems: ["paneer lababdaar", "dal makhani", "chaats", "tikkas", "kulfi"],
    sourceConfidence: "SassyHK 2025 推介；A-/B+",
    sourceUrl: "https://www.sassyhongkong.com/eat-drink-vegan-restaurants-veggie-friendly-health/",
  }),
  makeRestaurant({
    name: "OVO Cafe",
    district: "灣仔",
    category: "vegetarian",
    cuisine: "Vegetarian cafe",
    menuItems: ["vegetarian dishes", "soup of the day", "faux-meat dishes"],
    sourceConfidence: "SassyHK 2025 推介；B",
    sourceUrl: "https://www.sassyhongkong.com/eat-drink-vegan-restaurants-veggie-friendly-health/",
  }),
  makeRestaurant({
    name: "Veggie4Love",
    district: "中環",
    category: "vegetarian",
    cuisine: "素食 / fusion",
    menuItems: ["中西 fusion 素食主菜"],
    sourceConfidence: "SassyHK 2025 推介；B",
    sourceUrl: "https://www.sassyhongkong.com/eat-drink-vegan-restaurants-veggie-friendly-health/",
  }),
  makeRestaurant({
    name: "Thai Vegetarian Food",
    district: "九龍城",
    category: "vegetarian",
    cuisine: "泰式素食",
    menuItems: ["Thai vegetarian dishes", "set lunch"],
    sourceConfidence: "SassyHK 2025 推介；B",
    sourceUrl: "https://www.sassyhongkong.com/eat-drink-vegan-restaurants-veggie-friendly-health/",
  }),
  makeRestaurant({
    name: "無肉食 Ahimsa Buffet",
    district: "旺角",
    category: "vegetarian",
    cuisine: "素食 buffet",
    menuItems: ["Healthy Vegetarian Box A", "Healthy Vegetarian Box B", "Healthy Vegetarian Box C", "Healthy Vegetarian Box D", "素食 buffet / 飯盒"],
    sourceConfidence: "Foodpanda 顯示 vegetarian box；OpenRice 顯示旺角洗衣街分店為素食 / 無肉餐單；A 級",
    sourceUrl: "https://www.foodpanda.hk/restaurant/w6pk/ahimsa-buffet-mong-kok",
  }),
  makeRestaurant({
    name: "十三妹 Veggie Cafe",
    district: "旺角",
    category: "vegetarian",
    cuisine: "素食 cafe",
    menuItems: ["Earth Energy Bowl", "Future All Day Breakfast 等"],
    sourceConfidence: "Foodpanda / OpenRice 皆有資料；A-/B+",
    sourceUrl: "https://www.foodpanda.hk/restaurant/d2qj/13-mui-fusion-cafe-mong-kok-d2qj",
  }),
];
